services:
  - type: web
    plan: free
    name: joker
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: python3 ser.py & python3 -m JoKeRUB
    region: frankfurt
    envVars:
      - key: API_ID
        value: 40e7041d06ea7b6ee1cf39b3188b3452
      - key: API_HASH
        value: 9514755
      - key: TOKEN
        value: 7280847617:AAGg6zO5er3H0EmPPqemCUOJKoIrhkf282s
      - key: START_PIC
        value: https://telegra.ph/file/30849734c0436f1960e6a.jpg
      - key: CHAT
        value: -1002224282760
        
